"""dob fix

Revision ID: 0b895e9f31dd
Revises: 06c274d9304e
Create Date: 2024-10-16 23:18:15.448954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b895e9f31dd'
down_revision = '06c274d9304e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), nullable=True))
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
