"""empty message

Revision ID: 39e5aa954181
Revises: 
Create Date: 2024-10-16 15:11:41.408868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39e5aa954181'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_constraint('test_results_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'instances', ['instance_id'], ['instance_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('dob')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.DATE(), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('surname')

    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('test_results_ibfk_1', 'instances', ['instance_id'], ['instance_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
